#https://kanoki.org/2018/12/27/text-matching-cosine-similarity/

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import pandas as pd
count_vect = CountVectorizer()

nepal_domain=".blogger.com"\
"accounts.google.com"\
"accounts.google.com"\
".blogger.com"\
".blogger.com"\
".blogger.com"\
".facebook.com"\
".facebook.com"\
".google.com"\
".google.com"\
".google.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".www.netflix.com"\
".stackoverflow.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".stackoverflow.com"\
".stackoverflow.com"\
".stackoverflow.com"\
"www.wikipedia.org"\
".wikipedia.org"\
".wikipedia.org"\
".google.com.np"\
".google.com.np"\
".google.com.np"\
".yahoo.com"\
".yahoo.com"\
"www.yahoo.com"\
"www.yahoo.com"\
".yahoo.com"\
".yahoo.com"\
".yahoo.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".analytics.yahoo.com"\
".bluekai.com"\
".bluekai.com"\
".bluekai.com"\
".advertising.com"\
".demdex.net"\
".agkn.com"\
".agkn.com"\
".dpm.demdex.net"\
".yahoo.com"\
".yahoo.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
"accounts.google.com"\
"accounts.google.com"\
".doubleclick.net"\
".hamropatro.com"\
"www.hamropatro.com"\
".hamropatro.com"\
".hamropatro.com"\
".hamropatro.com"\
".hamropatro.com"\
".hamropatro.com"\
".twitter.com"\
".newsofnepal.com"\
".newsofnepal.com"\
".newsofnepal.com"\
".newsofnepal.com"\
".newsofnepal.com"\
".newsofnepal.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".sancharkendra.com"\
".sancharkendra.com"\
".sancharkendra.com"\
".sharethis.com"\
".sancharkendra.com"\
".sancharkendra.com"\
".sancharkendra.com"\
".khabarhub.com"\
".khabarhub.com"\
".khabarhub.com"\
".khabarhub.com"\
".khabarhub.com"\
".khabarhub.com"\
".khabarhub.com"\
"www.khabarhub.com"\
"www.khabarhub.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".khabarhub.com"\
".addthis.com"\
".addthis.com"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
"www.zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".google.com"\
"www.livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
"www.livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".livejasmin.com"\
".reportersnepal.com"\
".reportersnepal.com"\
".reportersnepal.com"\
".reportersnepal.com"\
".reportersnepal.com"\
".reportersnepal.com"\
".doubleclick.net"\
"www.reportersnepal.com"\
"www.reportersnepal.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".news24nepal.tv"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
".doubleclick.net"\
".google.com"\
".setopati.com"\
".setopati.com"\
".setopati.com"\
".sharethis.com"\
".twitter.com"\
".facebook.com"\
".setopati.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".t.sharethis.com"\
".exelator.com"\
".adsymptotic.com"\
".exelator.com"\
".adsrvr.org"\
".eyeota.net"\
".eyeota.net"\
".adsrvr.org"\
"sync.intentiq.com"\
"sync.intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
"sync1.intentiq.com"\
"sync1.intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".1rx.io"\
".janatasamachar.com"\
"www.janatasamachar.com"\
"www.janatasamachar.com"\
".janatasamachar.com"\
".janatasamachar.com"\
".janatasamachar.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".janatasamachar.com"\
".janatasamachar.com"\
".janatasamachar.com"\
".addthis.com"\
".addthis.com"\
".prasashan.com"\
"www.prasashan.com"\
"www.prasashan.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".prasashan.com"\
".prasashan.com"\
".prasashan.com"\
".prasashan.com"\
".prasashan.com"\
".addthis.com"\
".addthis.com"\
"www.microsoft.com"\
".microsoft.com"\
"www.microsoft.com"\
"www.microsoft.com"\
"www.microsoft.com"\
".microsoft.com"\
".microsoft.com"\
".microsoft.com"\
"www.microsoft.com"\
".microsoft.com"\
".microsoft.com"\
"www.microsoft.com"\
".onlinepana.com"\
"www.onlinepana.com"\
"www.onlinepana.com"\
".onlinepana.com"\
".onlinepana.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".onlinepana.com"\
".onlinepana.com"\
".onlinepana.com"\
".addthis.com"\
".addthis.com"\
".instagram.com"\
".instagram.com"\
".instagram.com"\
".ktmdainik.com"\
"ktmdainik.com"\
"ktmdainik.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".ktmdainik.com"\
".ktmdainik.com"\
".addthis.com"\
".facebook.com"\
".ktmdainik.com"\
".ktmdainik.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".ktmdainik.com"\
".esewa.com.np"\
".hamrobazaar.com"\
".ekantipur.com"\
".ekantipur.com"\
".ekantipur.com"\
".ekantipur.com"\
".facebook.com"\
".nayapage.com"\
".hamrokhelkud.com"\
".hamrokhelkud.com"\
".hamrokhelkud.com"\
"www.hamrokhelkud.com"\
"www.hamrokhelkud.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".hamrokhelkud.com"\
".hamrokhelkud.com"\
".hamrokhelkud.com"\
".hamrokhelkud.com"\
".addthis.com"\
".facebook.com"\
".addthis.com"\
".onlinekhabar.com"\
"www.onlinekhabar.com"\
"www.onlinekhabar.com"\
".addthis.com"\
".onlinekhabar.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".onlinekhabar.com"\
".addthis.com"\
".onlinekhabar.com"\
".onlinekhabar.com"\
".onlinekhabar.com"\
".koshionline.com"\
"www.koshionline.com"\
"www.koshionline.com"\
".addthis.com"\
".koshionline.com"\
".koshionline.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".koshionline.com"\
".koshionline.com"\
".koshionline.com"\
".facebook.com"\
".kathmandupati.com"\
"www.nepalkhabar.com"\
".nepalkhabar.com"\
".nepalkhabar.com"\
".nepalkhabar.com"\
".nepalkhabar.com"\
".nepalkhabar.com"\
"www.merokalam.com"\
"www.merokalam.com"\
"www.merokalam.com"\
"www.merokalam.com"\
"www.merokalam.com"\
"www.merokalam.com"\
"www.merokalam.com"\
".merokalam.com"\
".merokalam.com"\
".merokalam.com"\
".merokalam.com"\
".doubleclick.net"\
".doubleclick.net"\
".google.com"\
".facebook.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
".nepallive.com"\
".nepallive.com"\
".nepallive.com"\
".nepallive.com"\
".nepallive.com"\
".sharethis.com"\
".twitter.com"\
".t.sharethis.com"\
".exelator.com"\
".adsymptotic.com"\
".adsrvr.org"\
".exelator.com"\
".eyeota.net"\
".eyeota.net"\
".doubleclick.net"\
".adsrvr.org"\
"sync.intentiq.com"\
"sync.intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
"sync1.intentiq.com"\
"sync1.intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
"www.thahakhabar.com"\
".prixa.net"\
".thahakhabar.com"\
".thahakhabar.com"\
".thahakhabar.com"\
".thahakhabar.com"\
".thahakhabar.com"\
".coronanepal.live"\
".coronanepal.live"\
".sharethis.com"\
".coronanepal.live"\
".coronanepal.live"\
".coronanepal.live"\
".sharethis.com"\
".lokpath.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
".google.com"\
".doubleclick.net"\
".lokpath.com"\
".lokpath.com"\
".lokpath.com"\
".lokpath.com"\
".lokpath.com"\
".lokpath.com"\
"www.lokpath.com"\
"www.lokpath.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".lokpath.com"\
".addthis.com"\
".addthis.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
".doubleclick.net"\
".lokaantar.com"\
".lokaantar.com"\
".lokaantar.com"\
".lokaantar.com"\
".lokaantar.com"\
".lokaantar.com"\
".sharethis.com"\
".sharethis.com"\
"www.lokaantar.com"\
".prixa.net"\
".t.sharethis.com"\
".exelator.com"\
".adsymptotic.com"\
".exelator.com"\
".adsrvr.org"\
".eyeota.net"\
".eyeota.net"\
".adsrvr.org"\
"sync.intentiq.com"\
"sync.intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
"sync1.intentiq.com"\
"sync1.intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
".intentiq.com"\
"collector.effectivemeasure.net"\
"collector.effectivemeasure.net"\
"collector.effectivemeasure.net"\
"collector.effectivemeasure.net"\
".bbc.com"\
".bbc.com"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".imrworldwide.com"\
".imrworldwide.com"\
".bbc.com"\
".bbc.com"\
".doubleclick.net"\
".scorecardresearch.com"\
".scorecardresearch.com"\
"collector.effectivemeasure.net"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".bbc.com"\
".doubleclick.net"\
".bbc.com"\
"www.bbc.com"\
"www.bbc.com"\
"www.bbc.com"\
"www.bbc.com"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".skimresources.com"\
".skimresources.com"\
".agkn.com"\
"global.ib-ibi.com"\
".thrtle.com"\
".everesttech.net"\
"ib.mookie1.com"\
".ib.mookie1.com"\
".ib.mookie1.com"\
".www.bbc.com"\
"emp.bbc.com"\
".worldometers.info"\
".worldometers.info"\
".worldometers.info"\
".worldometers.info"\
".worldometers.info"\
".worldometers.info"\
".quantserve.com"\
".worldometers.info"\
".doubleclick.net"\
"www.worldometers.info"\
"www.worldometers.info"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".google.com"\
".arthasarokar.com"\
".arthasarokar.com"\
".arthasarokar.com"\
".arthasarokar.com"\
".arthasarokar.com"\
"www.baahrakhari.com"\
"www.baahrakhari.com"\
"baahrakhari.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
".baahrakhari.com"\
".baahrakhari.com"\
".doubleclick.net"\
".baahrakhari.com"\
".baahrakhari.com"\
".baahrakhari.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
"www.dcnepal.com"\
"www.dcnepal.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".dcnepal.com"\
".dcnepal.com"\
".addthis.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".dcnepal.com"\
".dcnepal.com"\
".dcnepal.com"\
".addthis.com"\
".doubleclick.net"\
".annapurnapost.com"\
".annapurnapost.com"\
".google.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"


india_vpn_domains= "www.wikipedia.org"\
".wikipedia.org"\
".wikipedia.org"\
".google.com"\
".google.com"\
".facebook.com"\
".facebook.com"\
".facebook.com"\
".facebook.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
"www.amazon.com"\
".youtube.com"\
".youtube.com"\
".youtube.com"\
".indiatimes.com"\
".indiatimes.com"\
"www.indiatimes.com"\
".indiatimes.com"\
".indiatimes.com"\
".facebook.com"\
"www.indiatimes.com"\
"www.indiatimes.com"\
".indiatimes.com"\
".doubleclick.net"\
"www.indiatimes.com"\
".indiatimes.com"\
".indiatimes.com"\
".indiatimes.com"\
".indiatimes.com"\
".amazon.in"\
".amazon.in"\
".amazon.in"\
".amazon.in"\
".amazon.in"\
"www.amazon.in"\
".amazon.in"\
".flipkart.com"\
".flipkart.com"\
".flipkart.com"\
".demdex.net"\
".flipkart.com"\
".flipkart.com"\
".flipkart.com"\
".flipkart.com"\
".yahoo.com"\
".yahoo.com"\
".yahoo.com"\
".yahoo.com"\
".yahoo.com"\
"www.yahoo.com"\
"www.yahoo.com"\
".analytics.yahoo.com"\
"www.yahoo.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".agkn.com"\
".advertising.com"\
".demdex.net"\
".bluekai.com"\
".bluekai.com"\
".bluekai.com"\
".dpm.demdex.net"\
".google.co.in"\
".google.co.in"\
".google.co.in"\
".instagram.com"\
".instagram.com"\
".instagram.com"\
".whatsapp.com"\
".www.whatsapp.com"\
".whatsapp.com"\
".onlinesbi.com"\
".onlinesbi.com"\
".onlinesbi.com"\
".stackoverflow.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".primevideo.com"\
".primevideo.com"\
".primevideo.com"\
"www.primevideo.com"\
".primevideo.com"\
"www.hotstar.com"\
"www.hotstar.com"\
"www.hotstar.com"\
"www.hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".hotstar.com"\
".doubleclick.net"\
".bing.com"\
".bat.bing.com"\
".hotstar.com"\
".hotstar.com"\
".facebook.com"\
".twitter.com"\
".worldometers.info"\
".worldometers.info"\
".worldometers.info"\
".worldometers.info"\
".worldometers.info"\
".doubleclick.net"\
".quantserve.com"\
".worldometers.info"\
".worldometers.info"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
".demdex.net"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
".dpm.demdex.net"\
".hdfcbank.com"\
".demdex.net"\
".doubleclick.net"\
".agkn.com"\
".rlcdn.com"\
".rlcdn.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".zeotap.com"\
".zeotap.com"\
".eyeota.net"\
".eyeota.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
".hdfcbank.com"\
"hbchat.senseforth.com"\
".hdfcbank.com"\
"hbsearch.senseforth.com"\
".facebook.com"\
".blogger.com"\
"accounts.google.com"\
"accounts.google.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".netflix.com"\
".www.netflix.com"\
".facebook.com"\
".www.linkedin.com"\
".linkedin.com"\
".linkedin.com"\
".www.linkedin.com"\
".linkedin.com"\
".linkedin.com"\
".www.linkedin.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".linkedin.com"\
".linkedin.com"\
".linkedin.com"\
".demdex.net"\
".linkedin.com"\
".linkedin.com"\
"www.microsoft.com"\
"www.microsoft.com"\
".microsoft.com"\
"www.microsoft.com"\
"www.microsoft.com"\
"www.microsoft.com"\
".microsoft.com"\
".microsoft.com"\
".microsoft.com"\
".microsoft.com"\
".microsoft.com"\
"www.microsoft.com"\
".demdex.net"\
".microsoft.com"\
".demdex.net"\
".twitter.com"\
".doubleclick.net"\
".dpm.demdex.net"\
".microsoft.com"\
".microsoft.com"\
".rlcdn.com"\
".adsrvr.org"\
".adsrvr.org"\
".rlcdn.com"\
".quantserve.com"\
".quantserve.com"\
".bing.com"\
".c.bing.com"\
".yahoo.com"\
".flashtalking.com"\
".tribalfusion.com"\
".postrelease.com"\
".postrelease.com"\
".owneriq.net"\
".owneriq.net"\
".rfihub.com"\
".rfihub.com"\
".rfihub.com"\
".rfihub.com"\
".3lift.com"\
".mathtag.com"\
"bttrack.com"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".crwdcntrl.net"\
".adentifi.com"\
".login.live.com"\
".login.live.com"\
"sync.srv.stackadapt.com"\
".srv.stackadapt.com"\
".office.com"\
"www.office.com"\
"www.office.com"\
"www.office.com"\
"www.office.com"\
"www.office.com"\
".microsoft.com"\
".microsoft.com"\
"www.office.com"\
"login.microsoftonline.com"\
".login.microsoftonline.com"\
"login.microsoftonline.com"\
"login.microsoftonline.com"\
".login.live.com"\
".login.live.com"\
"www.moneycontrol.com"\
"www.moneycontrol.com"\
"www.moneycontrol.com"\
"www.moneycontrol.com"\
"www.moneycontrol.com"\
"www.moneycontrol.com"\
"outlook.live.com"\
".live.com"\
".live.com"\
".microsoft.com"\
".microsoft.com"\
"outlook.live.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".twitter.com"\
".app.link"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
"www.zoom.us"\
".zoom.us"\
".zoom.us"\
"static.zoom.us"\
".zoom.us"\
".zoom.us"\
".zoom.us"\
"www.icicibank.com"\
"www.icicibank.com"\
"www.icicibank.com"\
"www.icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".icicibank.com"\
".doubleclick.net"\
".icicibank.com"\
".facebook.com"\
".nanorep.co"\
".icici.nanorep.co"\
"www.icicibank.com"\
".linkedin.com"\
".ads.linkedin.com"\
".linkedin.com"\
".icici.nanorep.co"\
".linkedin.com"\
".icicibank.com"\
".linkedin.com"\
".linkedin.com"\
".www.linkedin.com"\
".linkedin.com"\
".reddit.com"\
".reddit.com"\
".reddit.com"\
".reddit.com"\
".youtube.com"\
".youtube.com"\
".doubleclick.net"\
".aaxads.com"\
"www.reddit.com"\
"www.reddit.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".rlcdn.com"\
".rlcdn.com"\
".quantserve.com"\
".reddit.com"\
".bing.com"\
".bing.com"\
"www.bing.com"\
".bing.com"\
".bing.com"\
".bing.com"\
".bing.com"\
".bing.com"\
".bing.com"\
"github.com"\
".github.com"\
".github.com"\
".github.com"\
".manoramaonline.com"\
"www.manoramaonline.com"\
"www.manoramaonline.com"\
".udemy.com"\
".udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
".udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
".udemy.com"\
"www.udemy.com"\
"www.udemy.com"\
".udemy.com"\
".udemy.com"\
".udemy.com"\
".udemy.com"\
".intljs.rmtag.com"\
".intljs.rmtag.com"\
".www.udemy.com"\
".udemy.com"\
".udemy.com"\
".pointmediatracker.com"\
".udemy.com"\
".udemy.com"\
".udemy.com"\
".linksynergy.com"\
".linksynergy.com"\
".facebook.com"\
".rlcdn.com"\
".rlcdn.com"\
".dc-storm.com"\
"www.intoday.in"\
"www.indiatodaygroup.com"\
"www.indiatodaygroup.com"\
"www.indiatodaygroup.com"\
".indiatodaygroup.com"\
".indiatodaygroup.com"\
".indiatodaygroup.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".indiatoday.in"\
".indiatoday.in"\
".scorecardresearch.com"\
".scorecardresearch.com"\
"www.indiatoday.in"\
"www.indiatoday.in"\
".zedo.com"\
".zedo.com"\
".zedo.com"\
".zedo.com"\
".zedo.com"\
".zedo.com"\
".zedo.com"\
".izooto.com"\
".casalemedia.com"\
".casalemedia.com"\
".indiatoday.in"\
".doubleclick.net"\
".rubiconproject.com"\
"eus.rubiconproject.com"\
".adsrvr.org"\
".mathtag.com"\
".app.link"\
"id.sharedid.org"\
".yahoo.com"\
".rubiconproject.com"\
".intoday.in"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".adsrvr.org"\
".simpli.fi"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".pippio.com"\
".pippio.com"\
".pippio.com"\
".pippio.com"\
".quantserve.com"\
".quantserve.com"\
".pubmatic.com"\
".turn.com"\
".pubmatic.com"\
".rlcdn.com"\
".rlcdn.com"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".zerodha.com"\
".zerodha.com"\
".zerodha.com"\
".zerodha.com"\
"zerodha.com"\
".wordpress.com"\
".wordpress.com"\
".wordpress.com"\
".wordpress.com"\
"wordpress.com"\
".wordpress.com"\
".wordpress.com"\
".wordpress.com"\
".wordpress.com"\
".bing.com"\
".bat.bing.com"\
".wordpress.com"\
".wordpress.com"\
".doubleclick.net"\
".wordpress.com"\
".facebook.com"\
".wordpress.com"\
".ct.pinterest.com"\
".wordpress.com"\
".wordpress.com"\
".wordpress.com"\
".wordpress.com"\
".imdb.com"\
".imdb.com"\
".imdb.com"\
".imdb.com"\
"www.imdb.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
"www.naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".naukri.com"\
".doubleclick.net"\
".facebook.com"\
".quora.com"\
".quora.com"\
".quora.com"\
".quora.com"\
".quora.com"\
".quora.com"\
".quora.com"\
".quora.com"\
".quora.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".grammarly.com"\
".freepik.com"\
".www.freepik.com"\
".www.freepik.com"\
".freepik.com"\
".doubleclick.net"\
".freepik.com"\
".facebook.com"\
".freepik.com"\
".freepik.com"\
"www.freepik.com"\
".freepik.com"\
".freepik.com"\
".statcounter.com"\
".adform.net"\
".adform.net"\
".w3schools.com"\
".w3schools.com"\
".w3schools.com"\
".pubmatic.com"\
".connectad.io"\
".pubmatic.com"\
".pubmatic.com"\
".rubiconproject.com"\
"eus.rubiconproject.com"\
".openx.net"\
".lijit.com"\
".bidswitch.net"\
".casalemedia.com"\
".bidswitch.net"\
".bidswitch.net"\
".casalemedia.com"\
".pubmatic.com"\
".pubmatic.com"\
".ads.pubmatic.com"\
".sportradarserving.com"\
".sportradarserving.com"\
".sportradarserving.com"\
".connectad.io"\
".adform.net"\
".impact-ad.jp"\
".impact-ad.jp"\
".impact-ad.jp"\
"m.one.impact-ad.jp"\
"ads.playground.xyz"\
"ads.playground.xyz"\
".simpli.fi"\
".turn.com"\
".gumgum.com"\
".quantserve.com"\
".quantserve.com"\
"beacon.lynx.cognitivlabs.com"\
"beacon.lynx.cognitivlabs.com"\
".pubmatic.com"\
".doubleclick.net"\
".adsrvr.org"\
".demdex.net"\
".pubmatic.com"\
".pubmatic.com"\
".dpm.demdex.net"\
".pubmatic.com"\
".mathtag.com"\
".pubmatic.com"\
".adsrvr.org"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".tapad.com"\
".tapad.com"\
".pubmatic.com"\
".pubmatic.com"\
".rfihub.com"\
".rfihub.com"\
".rfihub.com"\
".rfihub.com"\
".casalemedia.com"\
".ctnsnet.com"\
".w55c.net"\
".pubmatic.com"\
".w55c.net"\
".tribalfusion.com"\
".pubmatic.com"\
".pubmatic.com"\
".pubmatic.com"\
".rubiconproject.com"\
".pubmatic.com"\
".advertising.com"\
".casalemedia.com"\
".casalemedia.com"\
".pippio.com"\
".pippio.com"\
".pippio.com"\
".pippio.com"\
".rlcdn.com"\
".rlcdn.com"\
".ads.pubmatic.com"\
".yahoo.com"\
".google.com"\
"www.w3schools.com"\
".aws.amazon.com"\
".amazon.com"\
".aws.amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazon.com"\
".amazonwebservices.d2.sc.omtrdc.net"\
".amazon.com"\
".amazon.com"\
".youtube.com"\
".youtube.com"\
"www.who.int"\
"www.who.int"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".addthis.com"\
".who.int"\
".taboola.com"\
".ndtv.com"\
".ndtv.com"\
".ndtv.com"\
".ndtv.com"\
".scorecardresearch.com"\
".scorecardresearch.com"\
".taboola.com"\
"www.ndtv.com"\
".ndtv.com"\
"www.ndtv.com"\
"www.ndtv.com"\
".ndtv.com"\
".doubleclick.net"\
".serving-sys.com"\
".ndtv.com"\
".ndtv.com"


corpus = [nepal_domain, india_vpn_domains]

X_train_counts = count_vect.fit_transform(corpus)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df = pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['nepal_domain', 'india_vpn_domains'])

df.to_html('filename.html')


vectorizer = TfidfVectorizer()
trsfm=vectorizer.fit_transform(corpus)
pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['nepal_domain', 'india_vpn_domains'])



print(pd.DataFrame(cosine_similarity(trsfm[0:2], trsfm),index=['nepal_domain', 'india_vpn_domains'], columns = ['nepal_domain', 'india_vpn_domains']))
